# Generated by Django 3.2.9 on 2021-12-06 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hosted_parties', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='parties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.CreateModel(
            name='Paycheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest.party')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('paycheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='rest.paycheck')),
            ],
        ),
    ]
