# Generated by Django 3.2.9 on 2021-12-07 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_alter_contribution_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='contribution',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
