# Generated by Django 3.2.9 on 2021-12-07 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_alter_contribution_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
