# Generated by Django 3.2.9 on 2021-12-07 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_alter_choice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='paycheck',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='rest.paycheck'),
            preserve_default=False,
        ),
    ]
