# Generated by Django 3.2.9 on 2022-04-06 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_choice_paycheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='paycheck',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='user',
        ),
        migrations.RemoveField(
            model_name='party',
            name='host',
        ),
        migrations.RemoveField(
            model_name='party',
            name='members',
        ),
        migrations.RemoveField(
            model_name='paycheck',
            name='party',
        ),
        migrations.RemoveField(
            model_name='record',
            name='paycheck',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
        migrations.DeleteModel(
            name='Party',
        ),
        migrations.DeleteModel(
            name='Paycheck',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
