# Generated by Django 3.2.9 on 2022-04-07 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_auto_20220407_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='billing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='rest.billing'),
        ),
    ]
